In [49]:
import tensorflow as tf
import numpy as np
import utils

In [2]:
a=tf.constant([[2]])
b=tf.constant([[3]])
result=tf.matmul(a,b)
print(result)

with tf.Session() as sess:
    output=sess.run(result)
    print(output)
    
print(output)

Tensor("MatMul:0", shape=(1, 1), dtype=int32)
[[6]]
[[6]]


In [3]:
t=tf.zeros((2,2))
print(t)
sess=tf.InteractiveSession()
print(t.eval())
sess.close()
tf.Variable(tf.zeros((2,2)),name='weights')

Tensor("zeros:0", shape=(2, 2), dtype=float32)
[[0. 0.]
 [0. 0.]]


<tf.Variable 'weights:0' shape=(2, 2) dtype=float32_ref>

In [4]:
#counter implementation
state=tf.Variable(0,name='counter')
new_value=tf.add(state,tf.constant(1))
update=tf.assign(state,new_value)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))
#         print(state.eval())

Instructions for updating:
Use `tf.global_variables_initializer` instead.
0
1
2
3


In [11]:
with tf.variable_scope("a"):
    tf.get_variable_scope().reuse_variables()
    #with tf.variable_scope('a',reuse=True)
    v=tf.get_variable("v6",[1,])
    s=tf.get_variable("v6")
    print(v.value)
    assert s==v
# print(v)

<bound method Variable.value of <tf.Variable 'a/v6:0' shape=(1,) dtype=float32_ref>>


In [12]:
tf.train.AdamOptimizer()

In [13]:
tf.InteractiveSession()
a=tf.zeros((2,))
a=tf.reshape(a,(1,-1))
a=a+1
print(a.eval())

[[1. 1.]]


In [35]:
n_samples=1000
batch_size=3

# x_data=np.reshape(x_data,(n_samples,-1))
# y_data=np.reshape(y_data,(n_samples,-1))

x=tf.placeholder(tf.float32,(batch_size,1))
y=tf.placeholder(tf.float32,(batch_size,1))

with tf.variable_scope("linear-regression",reuse=True):
    weight=tf.get_variable("weight",(1,1),initializer=tf.random_normal_initializer())
    bias=tf.get_variable("bias",(1,),initializer=tf.random_normal_initializer())
    y_predict=tf.matmul(x,weight)+bias
    loss=tf.reduce_sum((y_predict-y)**2/n_samples)
    optimizer=tf.train.AdamOptimizer().minimize(loss)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    for _ in range(10):
        indices=np.random.choice(n_samples,batch_size) # an array of size batch_size, each value is a random number in range(n_samples)
#         x_batch,y_batch=x_data[indices],y_data[indices]
#         x_batch=tf.constant([[1],[2],[3]],dtype=float)
        x_batch=np.array([[1],[2],[3]])
        y_batch=np.array([[1],[2],[3]])
        print(type(x_batch))
#         y_batch=tf.constant([[1],[2],[3]],dtype=float)
        _ ,loss_val=sess.run([optimizer,loss],feed_dict={x:x_batch,y:y_batch})

<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None
<class 'numpy.ndarray'>
None


In [59]:
import tensorflow.keras.preprocessing as preprocessing
from collections import Counter


with open('data.txt') as f:
    text=f.read()
    
print(text)
words=preprocessing.text.text_to_word_sequence(text, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~\n', lower=True, split=' ')
print(words)
word_counts=Counter(words)
print(word_counts)
list=[1]
print(list*2)

hello how are you?


thanks for choosing me...

hello again hello you
['hello', 'how', 'are', 'you', 'thanks', 'for', 'choosing', 'me', 'hello', 'again', 'hello', 'you']
Counter({'hello': 3, 'you': 2, 'how': 1, 'are': 1, 'thanks': 1, 'for': 1, 'choosing': 1, 'me': 1, 'again': 1})
[1, 1]


In [62]:
a=np.array([1,2,3])
print(a.shape)
a=a[:,None]
print(a,a.shape)
a=a[:,None]
print(a,a.shape)


(3,)
[[1]
 [2]
 [3]] (3, 1)
[[[1]]

 [[2]]

 [[3]]] (3, 1, 1)


In [65]:
a=2.2
print(type(a))
b=2
print(type(b))
a*b

<class 'float'>
<class 'int'>


4.4

In [2]:
a=[]
a.append([1,2,3])
print(a)
print(type(a))

[[1, 2, 3]]
<class 'list'>
